// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu18C4o9DJNnSBGzOTk6HqGfl6l_z8ugw',
    appId: '1:666803906483:web:dab295088db5c695d54dc6',
    messagingSenderId: '666803906483',
    projectId: 'precifica-ro-web',
    authDomain: 'precifica-ro-web.firebaseapp.com',
    storageBucket: 'precifica-ro-web.firebasestorage.app',
    measurementId: 'G-Y02MWJBXF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nLoT4AMks_tMbn7AzhNLCtRfpsCXLRk',
    appId: '1:666803906483:android:2169bf7a90fecff5d54dc6',
    messagingSenderId: '666803906483',
    projectId: 'precifica-ro-web',
    storageBucket: 'precifica-ro-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUC5-Dp2iA25AZlVqVkwnluL6yTWcsbUM',
    appId: '1:666803906483:ios:5d5855f5548ad45ed54dc6',
    messagingSenderId: '666803906483',
    projectId: 'precifica-ro-web',
    storageBucket: 'precifica-ro-web.firebasestorage.app',
    iosBundleId: 'com.example.precificaRoWeb',
  );
}
